### ISSUE TITLE
测试过imp和自定义结构体类型没

### ISSUE THREAD

**Issue by OCer** [Awhisper/VKMsgSend#10]
1、你这里是先取值 然后转成对象  再把对象转成相应类型  感觉绕了个弯  能不能直接根据参数类型去获取值而不需要转对象呢？
2、当参数不是按照方法声明的类型传进去的时候，取值会不对，甚至影响到了后续取值。如：
NSString *return4 = [abc VKCallSelectorName:@"testfunction:withB:withC:withD:" error:nil,4.9f,5.8f,nil, CGRectMake(10, 10, 10, 10)]; // 改为这个
NSLog(@"I'm testfunction: %d withB:%f withC:%@ withD:%@", num, boolv, str, NSStringFromCGRect(rect)); // 打印改为这个

**Comment by OCer** [comment]
- (NSString *)test:(id)test p1:(NSString *)p1 p2:(int)p2 p3:(double)p3 p4:(CGSize)p4 p5:(NSNull *)p5 p6:(void(^)(void))p6 p7:(BOOL)p7 p8:(char)p8 p9:(char *)p9 p10:(YY)p10 p11:(SEL)p11 p12:(void **)p12 p13:(void ***)p13 p14:(Class)p14 p15:(IMP)p15; // p6是block；p10是自定义结构体；p9是C的字符串 需测试正常字符串、""、NULL的情况
我想实现这个的调用  不知道有没有兴趣和我讨论  可以私聊给我微信或者QQ

**Comment by Awhisper** [comment]
@OCer 你说的是对的。。感觉是可以优化一下，直接把 va_list 透传给 vk_targetCallSelectorWithArgumentError  直接一次循环处理 methodSignature ，直接解 va_list 然后直接塞进 invocation

当时我是有别的想法。。。有可能不止提供给native使用，有可能提供给 rn（rn任意反射调用所有native带啊吗） 有可能提供给 web（网页任意反射调用native代码），这样的话他们的入参就不是va_list 了，而是一套我约束的包装对象，真正 CallSelectorWithArgumen 的核心逻辑输入参数，我选择了一种我包装过的对象


只不过 把反射能力提供给 web rn 的代码不在这个 repo 下，我起了个jsinvocation的项目，不过没上传代码=。=代码还在我本地

**Comment by OCer** [comment]
我把我的方法放上去 发现并没有调用？？？

**Comment by OCer** [comment]
- (id)VKCallSelectorName:(NSString *)selName error:(NSError *__autoreleasing *)error,...  
的实现里 为什么要用`[self class]`

**Comment by OCer** [comment]
其它的我都解决了 就差自定义结构体了

**Comment by OCer** [comment]
我搞定了  自定义结构体要搞成NSValue  总共200+行代码

**Comment by Awhisper** [comment]
赞 @OCer
