### ISSUE TITLE
好像不支持类方法的调用

### ISSUE THREAD

**Issue by ArmsZhou** [Awhisper/VKMsgSend#4]

**Comment by Awhisper** [comment]
VKMsgSend_ProjTests  测试用例中有3个类方法return的例子

这个例子相对原始

最新版本 有专门给类方法提供的 NSString的快捷API

直接把类名的 NSString 进行callselector

@interface NSString (VKMsgSend)
- (id)VKCallClassSelector:(SEL)selector error:(NSError *__autoreleasing *)error,...;
- (id)VKCallClassSelectorName:(NSString *)selName error:(NSError *__autoreleasing *)error,...;
- (id)VKCallClassAllocInitSelector:(SEL)selector error:(NSError *__autoreleasing *)error,...;
- (id)VKCallClassAllocInitSelectorName:(NSString *)selName error:(NSError *__autoreleasing *)error,...;

@end

**Comment by ArmsZhou** [comment]
不好意思，没问题的，是我调用错误了。

**Comment by ArmsZhou** [comment]
VKMsgSend 写的很棒！！
