### ISSUE TITLE
_vkMethodSignatureLock不会被创建

### ISSUE THREAD

**Issue by lishuailibertine** [Awhisper/VKMsgSend#6]
在多线程场景下vk_getMethodSignature这个静态方法里面的_vkMethodSignatureLock不会被创建，起不到同步作用（还是我没看到呢＝＝）。

**Comment by Awhisper** [comment]
我的god 。。我猪头了 特别感谢

**Comment by Awhisper** [comment]
最新的commit里已经 修复   3b28565e3e8365d767f210771925b356786a1db8

**Comment by lishuailibertine** [comment]
@Awhisper 好的👌
