### ISSUE TITLE
参数不支持二级指针传空，如NSError**、等类似的

### ISSUE THREAD

**Issue by madordie** [Awhisper/VKMsgSend#7]
RT。

如下函数：
```oc
+ (id)xxxOfError:(NSError *__autoreleasing *)error;
```
其参数必须使用`&err`形式，不支持传入`nil`。

**Comment by madordie** [comment]
很显然大佬及时[修复](https://github.com/Awhisper/VKMsgSend/commit/e61d71f6ff07f9f48c052a356d08f6e58d03f28b)了。膜... 👍

**Comment by Awhisper** [comment]
fixed
