### ISSUE TITLE
block invoke crash!

### ISSUE THREAD

**Issue by namo-py** [Awhisper/VKMsgSend#8]
您好，我使用了MsgSent对一个class A有一个实例方法init:(NSDictinary*)param，我在param里边传递了一个block，接收到之后执行block crash了，什么原因呢？

**Comment by Awhisper** [comment]
您好有具体的demo代码么？

**Comment by namo-py** [comment]
demo不方便贴出来，可以部分代码：
ClassA:
- (instancetype)__initWithParams:(NSDictionary *)params {
   //初始化略过
void(^callback)(void) = [params objectForKey:@“callback”];
        if (callback) {
            callback();
        }
};

ClassB:
NSDictionary *params =@{@"callback":[block copy]};
id classAInstance = [@"ClassA" VKCallClassAllocInitSelectorName:@"__initxxxx:" error:&error, params, nil];

然后就在invoke时crash

**Comment by Awhisper** [comment]
好的好的 我今天把这个case 跑一下 查一下为什么

**Comment by Awhisper** [comment]
@hujiaju 我测试了一下并没有发生崩溃，并且把测试代码提交到了git上去，你可以看一下最新的VC里面的 issueTest函数，但是block崩溃的原因可以推测一下，是否是block的信息不匹配，block本质是匿名函数，匿名函数有着自己的输入参数输出参数，而我用纯反射去传递block，我在我的工具层只能保证block作为一个id参数反射调用传递给使用者，但无法保证block的各种参数和使用方完全匹配
